# Generated by Django 3.0.6 on 2020-05-13 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EpidemicCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='国家名称')),
                ('confirm', models.IntegerField(verbose_name='累计确诊人数')),
                ('confirmIncr', models.IntegerField(verbose_name='新增确诊人数')),
                ('suspect', models.IntegerField(verbose_name='疑似人数')),
                ('dead', models.IntegerField(verbose_name='累计死亡人数')),
                ('deadIncr', models.IntegerField(verbose_name='新增死亡人数')),
                ('heal', models.IntegerField(verbose_name='累计治愈人数')),
                ('healIncr', models.IntegerField(verbose_name='新增治愈人数')),
                ('deadRate', models.FloatField(verbose_name='死亡率')),
                ('healRate', models.FloatField(verbose_name='治愈率')),
                ('detail_json_url', models.CharField(max_length=255, verbose_name='详细数据接口')),
                ('date', models.CharField(max_length=25, verbose_name='产生数据日期')),
            ],
        ),
        migrations.CreateModel(
            name='DetailEpidemicCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='国家名称')),
                ('confirm', models.IntegerField(verbose_name='累计确诊人数')),
                ('confirmIncr', models.IntegerField(verbose_name='新增确诊人数')),
                ('suspect', models.IntegerField(verbose_name='疑似人数')),
                ('suspectIncr', models.IntegerField(verbose_name='新增疑似人数')),
                ('dead', models.IntegerField(verbose_name='累计死亡人数')),
                ('deadIncr', models.IntegerField(verbose_name='新增死亡人数')),
                ('heal', models.IntegerField(verbose_name='累计治愈人数')),
                ('healIncr', models.IntegerField(verbose_name='新增治愈人数')),
                ('deadRate', models.FloatField(verbose_name='死亡率')),
                ('healRate', models.FloatField(verbose_name='治愈率')),
                ('date', models.CharField(max_length=25, verbose_name='产生数据日期')),
                ('e', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epidemic.EpidemicCountry', verbose_name='关联全球国家疫情模型')),
            ],
            options={
                'db_table': 'history_epidemic_country',
            },
        ),
    ]
