# Generated by Django 3.0.6 on 2020-05-13 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassFoodModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='食物名称')),
                ('img', models.ImageField(blank=True, null=True, upload_to='class_food', verbose_name='食物分类图片')),
            ],
            options={
                'db_table': 'class_food',
            },
        ),
        migrations.CreateModel(
            name='RecipeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(default='', max_length=25, verbose_name='食谱名称')),
                ('img', models.ImageField(upload_to='recipe', verbose_name='食谱图片')),
                ('content', models.CharField(default='', max_length=255, verbose_name='食谱内容')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('flag', models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否为每日一餐')),
                ('u_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'db_table': 'recipe',
            },
        ),
        migrations.CreateModel(
            name='FoodModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='食物名称')),
                ('img', models.ImageField(blank=True, null=True, upload_to='food', verbose_name='食物图片')),
                ('calorie', models.FloatField(default=0, verbose_name='卡路里值')),
                ('vitamin_a', models.FloatField(default=0, verbose_name='维A值')),
                ('vitamin_c', models.FloatField(default=0, verbose_name='维C值')),
                ('vitamin_e', models.FloatField(default=0, verbose_name='维E值')),
                ('vitamin_b1', models.FloatField(default=0, verbose_name='维B1值')),
                ('vitamin_b2', models.FloatField(default=0, verbose_name='维B2值')),
                ('protein', models.FloatField(default=0, verbose_name='蛋白质值')),
                ('axunge', models.FloatField(default=0, verbose_name='脂肪值')),
                ('carbohydrate', models.FloatField(default=0, verbose_name='碳水化合物值')),
                ('dietary_fiber', models.FloatField(default=0, verbose_name='膳食纤维值')),
                ('f_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.ClassFoodModel', verbose_name='关联食物分类')),
            ],
            options={
                'db_table': 'food',
            },
        ),
    ]
