# Generated by Django 3.0.6 on 2020-05-13 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassFoodModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='食物名称')),
                ('img', models.ImageField(blank=True, null=True, upload_to='class_food', verbose_name='食物分类图片')),
            ],
            options={
                'db_table': 'class_food',
            },
        ),
        migrations.CreateModel(
            name='FoodModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='食物名称')),
                ('img', models.ImageField(blank=True, null=True, upload_to='food', verbose_name='食物图片')),
                ('f_calorie', models.FloatField(default=0, verbose_name='食物含有卡路里值')),
                ('f_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.ClassFoodModel', verbose_name='关联食物分类')),
            ],
            options={
                'db_table': 'food',
            },
        ),
        migrations.CreateModel(
            name='RecipeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(max_length=25, verbose_name='食谱名称')),
                ('r_calorie', models.FloatField(default=0, verbose_name='食谱含有卡路里值')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('flag', models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否为每日一餐')),
                ('r_food1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_org1', to='recipe.FoodModel', verbose_name='关联食物')),
                ('r_food2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_org2', to='recipe.FoodModel', verbose_name='关联食物')),
                ('r_food3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_org3', to='recipe.FoodModel', verbose_name='关联食物')),
                ('r_food4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_org4', to='recipe.FoodModel', verbose_name='关联食物')),
                ('r_food5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_org5', to='recipe.FoodModel', verbose_name='关联食物')),
                ('u_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'db_table': 'recipe',
            },
        ),
    ]
